# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: MyGitHubRepo # The name used to reference this repository in the checkout step
    type: github
    endpoint: https://github.com/asengupta28/raboassignment
    name: asengupta28/raboassignment

trigger:
- main

pool:
  name: Agent-self-hosted
  demands: maven

steps:
- checkout: MyGitHubRepo

steps:
- task: Maven@3
  displayName: 'Maven pom.xml'
  inputs:
    mavenPomFile: '$(Parameters.mavenPOMFile)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(BUILD_TARGETDIRECTORY)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/*.jar'
    TargetFolder: '$(BUILD_TARGETDIRECTORY)'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    publishLocation: FilePath
    TargetPath: 'E:\Avijit\lanosrep\erawtfoS\Azure Pipeline\win-agent'
  condition: succeededOrFailed()
